-- Complete schema for a FRESH Postgres database (RDS or local).
-- Requires: Postgres 13+ (gen_random_uuid is built in) and the pg_trgm extension.
--
--   psql "$DATABASE_URL" -f deploy/schema.sql     (or: npm run db:schema)
--
-- This file is the single source of truth for a new environment. To upgrade an
-- EXISTING database, apply the files in deploy/migrations/ instead; to move data
-- between environments, use pg_dump/pg_restore.

create extension if not exists pg_trgm;

-- ---------- samples: imported bank questions ----------
create table if not exists samples (
  id            uuid primary key default gen_random_uuid(),
  source_file   text not null,
  topic         text not null,
  difficulty    text not null,
  type          text not null,
  language      text,
  question      text not null,
  options       jsonb not null,
  correct_index integer not null,
  code          text,
  created_at    timestamptz not null default now(),
  team          text,
  uploaded_by   text
);
create index if not exists samples_source_file_idx on samples (source_file);
create index if not exists samples_language_idx on samples (language);
create index if not exists samples_team_idx on samples (team);
create index if not exists samples_topic_trgm_idx on samples using gin (topic gin_trgm_ops);

-- ---------- runs: one row per generation ----------
create table if not exists runs (
  id                     uuid primary key default gen_random_uuid(),
  status                 text not null default 'pending',
  topic                  text not null,
  difficulty             text not null,
  mcq_type               text not null,
  count                  integer not null,
  quality                text not null,
  languages              jsonb not null default '[]'::jsonb,
  sample_file_ids        jsonb not null default '[]'::jsonb,
  samples_per_file       integer not null default 4,
  max_revamp_attempts    integer not null default 3,
  error_message          text,
  started_at             timestamptz not null default now(),
  finished_at            timestamptz,
  team                   text,
  mode                   text default 'sample',
  grounded               boolean default false,
  question_kinds         jsonb default '[]'::jsonb,
  extra_prompt           text,
  negative_prompt        text,
  finalised_at           timestamptz,
  finalised_by           text,
  published_at           timestamptz,
  published_by           text,
  created_by             uuid,
  created_by_name        text,
  prompt_profile_version integer,
  attachments            jsonb not null default '[]'::jsonb
);
create index if not exists runs_started_at_idx on runs (started_at desc);
create index if not exists runs_status_idx on runs (status);
create index if not exists runs_team_idx on runs (team);

-- ---------- mcqs: generated questions ----------
create table if not exists mcqs (
  id                  uuid primary key default gen_random_uuid(),
  run_id              uuid not null references runs(id) on delete cascade,
  index               integer not null,
  type                text not null,
  topic               text not null,
  difficulty          text not null,
  question            text not null,
  options             jsonb not null,
  correct_index       integer not null,
  explanation         text,
  snippet_language    text,
  snippet_code        text,
  plag_status         text not null default 'pending',
  plag_matches        jsonb not null default '[]'::jsonb,
  plag_attempts       integer not null default 0,
  created_at          timestamptz not null default now(),
  parent_sample_id    uuid,
  diversity_status    text default 'ok',
  answer_check_status text,
  answer_check_index  integer,
  answer_check_notes  text,
  image_svg           text,
  review_status       text,
  reviewed_by         text,
  reviewed_at         timestamptz,
  review_reason       text,
  original_question   text,
  unique (run_id, index)
);
create index if not exists mcqs_run_id_idx on mcqs (run_id);
create index if not exists mcqs_parent_sample_idx on mcqs (parent_sample_id);

-- ---------- run_events: SSE replay log ----------
create table if not exists run_events (
  id     bigint generated by default as identity primary key,
  run_id uuid not null references runs(id) on delete cascade,
  type   text not null,
  data   jsonb not null,
  ts     timestamptz not null default now()
);
create index if not exists run_events_run_id_ts_idx on run_events (run_id, ts);

-- ---------- plag_corpus: scraped public MCQs ----------
create table if not exists plag_corpus (
  id            bigint generated by default as identity primary key,
  source        text not null,
  url           text not null,
  topic         text,
  language      text,
  question      text not null,
  question_norm text not null,
  code          text,
  created_at    timestamptz not null default now(),
  unique (source, url)
);
create index if not exists plag_corpus_language_idx on plag_corpus (language);
create index if not exists plag_corpus_source_idx on plag_corpus (source);
create index if not exists plag_corpus_q_trgm_idx on plag_corpus using gin (question_norm gin_trgm_ops);

create or replace function match_plag_trgm(query_text text, match_count integer default 5, filter_language text default null)
returns table(id bigint, source text, url text, question text, similarity double precision)
language sql stable
as $function$
  select
    pc.id,
    pc.source,
    pc.url,
    pc.question,
    similarity(pc.question_norm, lower(regexp_replace(query_text, '\s+', ' ', 'g'))) as similarity
  from plag_corpus pc
  where (filter_language is null or pc.language = filter_language)
    and pc.question_norm % lower(regexp_replace(query_text, '\s+', ' ', 'g'))
  order by similarity desc
  limit match_count
$function$;

-- ---------- tags ----------
create table if not exists tags (
  id         uuid primary key default gen_random_uuid(),
  team       text not null,
  name       text not null,
  color      text not null default '#7AB52C',
  created_by uuid,
  created_at timestamptz not null default now(),
  unique (team, name)
);
create index if not exists tags_team_idx on tags (team);

create table if not exists tag_items (
  id         uuid primary key default gen_random_uuid(),
  tag_id     uuid not null references tags(id) on delete cascade,
  item_type  text not null,
  item_id    text not null,
  created_at timestamptz not null default now(),
  unique (tag_id, item_type, item_id)
);
create index if not exists tag_items_tag_id_idx on tag_items (tag_id);

-- ---------- users: accounts, credentials and team grants ----------
-- The application is its own identity provider. Passwords are bcrypt hashes
-- (cost 12) written only by lib/auth.ts; sessions are HS256 JWTs signed with
-- AUTH_JWT_SECRET and held in an httpOnly cookie — nothing is stored here.
-- Provision accounts with `npm run user:create`.
create table if not exists users (
  id                  uuid primary key default gen_random_uuid(),
  email               text not null,
  password_hash       text not null,
  full_name           text,
  -- Primary team. 'ALL' grants visibility of every team.
  team                text not null check (team = any (array['HACK','Cognitive','Domain','Psychometric','SEG','ALL'])),
  -- Extra team grants beyond the primary one (e.g. team 'Cognitive' + {'SEG'}).
  teams               text[] not null default '{}',
  is_active           boolean not null default true,
  created_at          timestamptz not null default now(),
  last_login_at       timestamptz
);
-- Case-insensitive uniqueness without requiring the citext extension.
create unique index if not exists users_email_key on users (lower(email));
