#!/usr/bin/env python3
"""Build a single-file HTML preview of all generated MCQs.

Reads every JSON in generated/ and embeds the data into preview.html.
Open the file in any browser — no server needed.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN_DIR = ROOT / "generated"
OUT = ROOT / "preview.html"

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Generated MCQs Preview</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<script src="https://cdn.tailwindcss.com"></script>
<style>
  pre { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  .badge { font-size: 11px; padding: 2px 8px; border-radius: 999px; font-weight: 500; }
  .diff-EASY      { background:#dcfce7; color:#166534; }
  .diff-MEDIUM    { background:#fef9c3; color:#854d0e; }
  .diff-DIFFICULT { background:#fee2e2; color:#991b1b; }
  .option { border:1px solid #e5e7eb; border-radius:8px; padding:8px 12px; }
  .option.correct { border-color:#16a34a; background:#f0fdf4; }
  details > summary { cursor: pointer; }
</style>
</head>
<body class="bg-slate-50 text-slate-900">
<div class="max-w-5xl mx-auto p-6">
  <header class="mb-6">
    <h1 class="text-2xl font-semibold">Generated MCQs Preview</h1>
    <p class="text-sm text-slate-500">__TOTAL__ MCQs across __TOPICS__ topics. Generated by the MCQ workflow + plag/code verifiers.</p>
  </header>

  <div class="flex flex-wrap gap-3 mb-4 items-center">
    <input id="search" class="flex-1 min-w-[240px] px-3 py-2 border rounded-md text-sm" placeholder="Search question text or options…" />
    <select id="topic" class="px-3 py-2 border rounded-md text-sm bg-white">
      <option value="">All topics</option>
    </select>
    <select id="difficulty" class="px-3 py-2 border rounded-md text-sm bg-white">
      <option value="">All difficulties</option>
      <option>EASY</option><option>MEDIUM</option><option>DIFFICULT</option>
    </select>
    <label class="text-sm flex items-center gap-2">
      <input id="showAnswer" type="checkbox" checked /> Show correct
    </label>
  </div>

  <div id="stats" class="text-xs text-slate-500 mb-3"></div>
  <div id="list" class="space-y-4"></div>
</div>

<script>
const DATA = __DATA__;

const DIFF_NORM = { easy:'EASY', medium:'MEDIUM', hard:'DIFFICULT',
                    EASY:'EASY', MEDIUM:'MEDIUM', DIFFICULT:'DIFFICULT' };

function esc(s) { return (s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }

const topicSet = new Set(DATA.map(m => m.topic));
const topicSel = document.getElementById('topic');
[...topicSet].sort().forEach(t => {
  const o = document.createElement('option'); o.value = t; o.textContent = t; topicSel.appendChild(o);
});

function render() {
  const q     = document.getElementById('search').value.trim().toLowerCase();
  const topic = document.getElementById('topic').value;
  const diff  = document.getElementById('difficulty').value;
  const show  = document.getElementById('showAnswer').checked;

  const filtered = DATA.filter(m => {
    if (topic && m.topic !== topic) return false;
    if (diff  && DIFF_NORM[m.difficulty] !== diff) return false;
    if (!q) return true;
    const hay = (m.question + ' ' + (m.options||[]).join(' ') + ' ' + (m.code||'')).toLowerCase();
    return hay.includes(q);
  });

  document.getElementById('stats').textContent = `${filtered.length} of ${DATA.length} MCQs`;

  const list = document.getElementById('list');
  list.innerHTML = filtered.map((m, i) => {
    const d = DIFF_NORM[m.difficulty] || 'MEDIUM';
    const opts = (m.options || []).map((o, idx) => {
      const isCorrect = idx === m.correct_index;
      const cls = show && isCorrect ? 'option correct' : 'option';
      const mark = show && isCorrect ? '<span class="text-green-700 font-semibold mr-2">✓</span>' : '';
      return `<div class="${cls}"><span class="text-slate-400 mr-2">${String.fromCharCode(65+idx)}.</span>${mark}${esc(o)}</div>`;
    }).join('');
    const code = m.code ? `<pre class="bg-slate-900 text-slate-100 text-xs p-3 rounded-md overflow-auto mt-3"><code>${esc(m.code)}</code></pre>` : '';
    const lang = m.language ? `<span class="badge bg-slate-200 text-slate-700">${esc(m.language)}</span>` : '';
    return `
      <article class="bg-white rounded-lg border border-slate-200 p-4 shadow-sm">
        <header class="flex flex-wrap items-center gap-2 mb-2">
          <span class="text-xs text-slate-400">#${i+1}</span>
          <span class="badge diff-${d}">${d}</span>
          ${lang}
          <span class="text-xs text-slate-500 ml-auto">${esc(m.topic)}</span>
        </header>
        <div class="whitespace-pre-wrap text-sm leading-relaxed">${esc(m.question)}</div>
        ${code}
        <div class="grid sm:grid-cols-2 gap-2 mt-3 text-sm">${opts}</div>
      </article>`;
  }).join('') || '<div class="text-slate-400 text-sm">No matches.</div>';
}

['search','topic','difficulty','showAnswer'].forEach(id => {
  const el = document.getElementById(id);
  el.addEventListener('input', render);
  el.addEventListener('change', render);
});
render();
</script>
</body>
</html>
"""


def main() -> int:
    files = sorted(GEN_DIR.glob("*.json"))
    all_mcqs: list[dict] = []
    for fp in files:
        try:
            data = json.loads(fp.read_text())
        except Exception as e:
            print(f"skip {fp.name}: {e}", file=sys.stderr)
            continue
        if isinstance(data, list):
            all_mcqs.extend(data)

    topics = {m.get("topic", "") for m in all_mcqs}
    html = (HTML_TEMPLATE
            .replace("__DATA__", json.dumps(all_mcqs, ensure_ascii=False))
            .replace("__TOTAL__", str(len(all_mcqs)))
            .replace("__TOPICS__", str(len(topics))))
    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {len(all_mcqs)} MCQs across {len(topics)} topics → {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
