-- 006 — diagram-as-code inline SVG.
--
-- When a run has create_images = true, each question that genuinely needs a
-- visual gets ONE self-contained inline <svg> diagram generated by Claude (not
-- a diffusion model). It is stored verbatim and rendered directly in the review
-- board. Most questions need no diagram, so this is null for the majority.
--
-- Written best-effort (the runner's image persist is wrapped in bestEffortUpdate,
-- so generation still completes before this is applied). Apply via the Supabase
-- dashboard SQL editor or MCP.

alter table mcqs add column if not exists image_svg text;
